version: "3.3"

services:
  webapi:
    build:
      context: ./
    ports:
      - 5001:5001

  fr-mysql:
    container_name: fr-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always
